language: python
# Make Python 3.5 and 3.6 available:
python: 3.7
# Travis workaround to support newer versions of python
sudo: required
dist: xenial
# See tox.ini for env list
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy
    - env: TOXENV=flake
    - env: TOXENV=checkmanifest
install:
- pip install tox>=2.1 'virtualenv<17'
script:
- tox